"""Inicializando o esquema do banco de dados

Revision ID: c8747e7a5c39
Revises: 
Create Date: 2024-11-18 22:33:31.672763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8747e7a5c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('especializacao', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('historico_medico', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=True),
    sa.Column('perfil', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('data_consulta', sa.DateTime(), nullable=False),
    sa.Column('motivo_consulta', sa.String(length=255), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('prescricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_exame', sa.String(length=100), nullable=False),
    sa.Column('data_exame', sa.Date(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(length=255), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('enviada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('exames')
    op.drop_table('consultas')
    op.drop_table('usuarios')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    # ### end Alembic commands ###
